# overlays\staging\services\gateway\kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../base/services/gateway

configMapGenerator:
- behavior: merge
  envs:
  - gateway.env
  name: gateway-config

images:
- name: ghcr.io/zerodayz7/obywatel-gateway
  newName: ghcr.io/zerodayz7/obywatel-gateway
  newTag: 27dd283
- name: zerodayz7/obywatel-gateway
  newName: ghcr.io/zerodayz7/obywatel-gateway
  newTag: 1279ebf

patches:
- path: patch-resources.yaml
  target:
    kind: Deployment
    name: gateway
- path: patch-env.yaml
  target:
    kind: Deployment
    name: gateway
