# overlays\staging\services\gateway\kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/services/gateway

images:
  - name: zerodayz7/obywatel-gateway
    newTag: aac3b24

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: gateway
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: gateway
