# overlays/staging/services/auth-service/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obywatel-staging

resources:
  - ../../../../base/services/auth-service

configMapGenerator:
  - behavior: merge
    envs:
      - auth-service.env
    name: auth-config

images:
  - name: ghcr.io/zerodayz7/obywatel-auth
    newName: ghcr.io/zerodayz7/obywatel-auth
    newTag: 27dd283

patches:
  - path: patch-resources.yaml
    target:
      kind: Deployment
      name: auth-service
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: auth-service
