# k3s-gitops-infra/overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obywatel-staging

resources:
  - shared/
  - infra/databases/db-auth
  - infra/cache/redis-auth
  - services/auth
  - services/gateway
  # - services/citizen-docs
  # - services/notification-service
