namespace: obywatel-plus-production

resources:
  - ../../base
  - namespace.yaml
  - ingress.yaml

patches:
  - path: patches/auth-env.yaml
    target:
      kind: Deployment
      name: auth-service
