# base\services\gateway\configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  PORT: "8081"
  LOG_LEVEL: "info"
  AUTH_SERVICE_ADDR: "http://auth-service:8082"
  REDIS_HOST: "redis-auth"
  REDIS_PORT: "6379"
