# base\services\gateway\configmap.yaml
apiVersion: v1
kind: ConfigMapco
metadata:
  name: gateway-config
data:
  PORT: "8081"
  LOG_LEVEL: "info"
  AUTH_SERVICE_URL: "http://auth-service:8082"
  REDIS_URL: "redis-auth:6379"
  REDIS_ADDR: "redis-auth:6379"
