# overlays/staging/databases/postgres-auth/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/databases/postgres-auth

patches:
  - path: patch-storage.yaml
