apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-citizen-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-citizen-docs
  template:
    metadata:
      labels:
        app: db-citizen-docs
    spec:
      containers:
        - name: database
          image: postgres:18.3-alpine
          ports:
            - containerPort: 5432
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-citizen-docs-secret
                  key: database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-citizen-docs-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-citizen-docs-secret
                  key: password
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-citizen-docs-pvc
