# base\services\auth-service\configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  PORT: "8082"
  LOG_LEVEL: "info"
  DB_HOST: "db-auth"
  DB_PORT: "5432"
  DB_NAME: "obywatel_auth"
  REDIS_HOST: "redis-auth"
  REDIS_PORT: "6379"
