apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/zerodayz7/obywatel-auth
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: auth-config
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-auth-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-auth-secret
                  key: password
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth-secret
                  key: password
            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: JWT_ACCESS_SECRET
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: JWT_REFRESH_SECRET
            - name: INTERNAL_HMAC_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: INTERNAL_HMAC_SECRET
            - name: INTERNAL_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: INTERNAL_ENCRYPTION_KEY
            - name: INTERNAL_HASH_SALT
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: INTERNAL_HASH_SALT
          resources:
            limits:
              cpu: "300m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
