resources:
  - services/auth-service
  - services/citizen-docs
  - services/gateway
  - services/notification-service
  - services/citizen-api

  - infra/databases/db-auth
  - infra/databases/db-citizen-docs
  - infra/databases/db-notification

  - infra/cache/redis-auth
