# overlays/staging/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obywatel-staging

resources:
  - infra/namespaces
  - infra/databases/db-auth
  - infra/cache/redis-auth
  - services/gateway
  # - services/auth-service
  # - services/citizen-docs
  # - services/notification-service
  # - services/citizen-api

labels:
  - includeSelectors: true
    pairs:
      env: staging
      managed-by: argo-cd
      project: obywatel-plus

# CENTRALNE STEROWANIE SKALOWANIEM
replicas:
  - name: gateway
    count: 1

  # - name: auth-service
  #   count: 1

  - name: db-auth
    count: 1

  - name: redis-auth
    count: 1
